template: esphome-dlms-austria
product:
  identifier: esphome-dlms-meter-austria
  brand: ESPHome
  description: DLMS Meter Austria
description: |
  Requires an ESPHome node running the `dlms_meter` component (e.g., from `github://SimonFischer04/esphome@dlms-meter`),
  configured for Austrian DLMS meters.

render:
  - usage: grid
    default: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP address or hostname
    advanced: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP address or hostname
      timeout: 10s # Timeout, optional
params:
  - name: host
    example: 192.0.2.2
    default:
    choice: []
    unit:
    description: IP address or hostname
    help:
    advanced: false
    optional: false
  - name: timeout
    example: 10s
    default: 10s
    choice: []
    unit:
    description: Timeout
    help:
    advanced: true
    optional: true