template: esphome-dlms-austria
product:
  identifier: esphome-dlms-meter-austria
  brand: ESPHome
  description: DLMS Meter Austria
description: |
  Benötigt ein ESPHome Gerät mit der `dlms_meter` Komponente (z.B. von `github://SimonFischer04/esphome@dlms-meter`),
  konfiguriert für österreichische DLMS-Zähler.

render:
  - usage: grid
    default: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP-Adresse oder Hostname
    advanced: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP-Adresse oder Hostname
      timeout: 10s # Zeitüberschreitung, optional
params:
  - name: host
    example: 192.0.2.2
    default:
    choice: []
    unit:
    description: IP-Adresse oder Hostname
    help:
    advanced: false
    optional: false
  - name: timeout
    example: 10s
    default: 10s
    choice: []
    unit:
    description: Zeitüberschreitung
    help:
    advanced: true
    optional: true