name: build-deploy

permissions: {}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: depot-ubuntu-24.04-arm-8
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
