name: openapi-validate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "static/rest-api.yaml"
      - ".github/workflows/openapi-validate.yml"
  push:
    paths:
      - "static/rest-api.yaml"
      - ".github/workflows/openapi-validate.yml"

jobs:
  validate-openapi:
    name: Validate OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate OpenAPI spec
        run: go run github.com/getkin/kin-openapi/cmd/validate@latest -- static/rest-api.yaml
