name: openapi-validate

on:
  pull_request:
    paths:
      - "static/rest-api.yaml"
      - ".github/workflows/openapi-validate.yml"

jobs:
  validate-openapi:
    name: Validate OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download openapi-mcp
        run: |
          curl -L https://github.com/jedisct1/openapi-mcp/releases/download/latest/openapi-mcp_Darwin_x86_64.tar.gz -o openapi-mcp
          chmod +x openapi-mcp
      - name: Validate OpenAPI spec
        run: ./openapi-mcp validate static/rest-api.yaml
