name: openapi-validate

on:
  pull_request:
    paths:
      - "static/rest-api.yaml"
      - ".github/workflows/openapi-validate.yml"

jobs:
  validate-openapi:
    name: Validate OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: mbowman100/swagger-validator-action@master
        with:
          files: static/rest-api.yaml
